config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/address')
  get '/logout', to: "main#logout"
  get '/auth/:provider/callback', to: "main#omniauth_callback", as: :omniauth_callback
  get '/address', to: "main#address"
  post '/address', to: "main#address_locator"
  get '/ip', to: "main#ip"
  post '/ip', to: "main#ip_locator"
  get '/pure', to: "main#pure"
  post '/pure', to: "main#pure_locator"
  get '/reverse', to: "main#reverse"
  post '/reverse', to: "main#reverse_query"
  get '/geolocate', to: "main#geolocate"
  get '/history', to: "main#history"
  get '/get_i18n', to: "main#get_i18n"
  post '/api/address', to: "api#address"
  post '/api/ip', to: "api#ip"
  post '/api/pure', to: "api#pure"
  post '/api/reverse', to: "api#reverse"
end

app/controllers/main_controller.rb
class MainController < ApplicationController

    before_filter :find_user
    before_filter :user_only, only: :history

    def address
        @loc = AddressLocation.new
        @main_nav_active = :address
    end

    def address_locator
        @loc = AddressLocation.find_by_address(params[:address_location][:address])
        @loc ||= AddressLocation.create(params.require(:address_location).permit(:address))
        @main_nav_active = :address
        if @loc.latitude.blank? || @loc.longitude.blank?
            if request.xhr?
                render json: {error: :empty_coordinates} and return
            else
                flash[:error] = t("errors.empty_coordinates")
                render :address and return
            end
        end
        if @loc.locator.blank?
            @loc.locator = Rlqth::Utils.locator_from_dimensions(@loc.latitude, @loc.longitude)[0..5]
            @loc.save!
        end
        if !@user.blank?
            HistoricalQuery.create(remote_user: @user, location: @loc)
        end
        if request.xhr?
            render json: @loc
        else
            render :result
        end
    end

    def ip
        @loc = IpLocation.new
        @main_nav_active = :ip
    end

    def ip_locator
        @loc = IpLocation.find_by_ip(params[:ip_location][:ip])
        @loc ||= IpLocation.create(params.require(:ip_location).permit(:ip))
        @main_nav_active = :ip
        if @loc.latitude.blank? || @loc.longitude.blank?
            if request.xhr?
                render json: {error: :empty_coordinates} and return
            else
                flash[:error] = t("errors.empty_coordinates")
                render :ip and return
            end
        end
        if @loc.locator.blank?
            @loc.locator = Rlqth::Utils.locator_from_dimensions(@loc.latitude, @loc.longitude)[0..5]
            @loc.save!
        end
        if !@user.blank?
            HistoricalQuery.create(remote_user: @user, location: @loc)
        end
        if request.xhr?
            render json: @loc
        else
            render :result
        end
    end

    def pure
        @loc = PureLocation.new
        @main_nav_active = :pure
    end

    def pure_locator
        @loc = PureLocation.where(latitude: params[:pure_location][:latitude], longitude: params[:pure_location][:longitude]).first
        @loc ||= PureLocation.create(params.require(:pure_location).permit(:latitude, :longitude))
        @main_nav_active = :pure
        if @loc.latitude.blank? || @loc.longitude.blank?
            if request.xhr?
                render json: {error: :empty_coordinates} and return
            else
                flash[:error] = t("errors.empty_coordinates")
                render :pure and return
            end
        end
        if @loc.locator.blank?
            @loc.locator = Rlqth::Utils.locator_from_dimensions(@loc.latitude, @loc.longitude)[0..5]
            @loc.save!
        end
        if !@user.blank?
            HistoricalQuery.create(remote_user: @user, location: @loc)
        end
        if request.xhr?
            render json: @loc
        else
            render :result
        end
    end

    def reverse
        @loc = ReverseLocation.new
        @main_nav_active = :reverse
    end

    def reverse_query
        @loc = ReverseLocation.where(locator: params[:reverse_location][:locator]).first
        @loc ||= ReverseLocation.create(params.require(:reverse_location).permit(:locator))
        @main_nav_active = :reverse
        if !@user.blank?
            HistoricalQuery.create(remote_user: @user, location: @loc)
        end
        if request.xhr?
            render json: @loc
        else
            render :reverse_result
        end
    end

    def geolocate
    end

    def history
        @hqs = HistoricalQuery.where(remote_user_id: @user.id).order(updated_at: :desc).page(params[:page])
    end

    def omniauth_callback
        if !auth_hash.nil?
            @user = RemoteUser.find_by_callsign(auth_hash.info.callsign)
            if @user.nil?
                @user = RemoteUser.create(callsign: auth_hash.info.callsign, email: auth_hash.info.email)
                @user.reload
            end
            @session = RemoteSession.new
            @session.token = auth_hash.credentials.token
            @session.token_expires = Time.at(auth_hash.credentials.expires_at)
            @session.refresh_token = auth_hash.credentials.refresh_token
            @session.remote_user = @user
            @session.save!
            @user.save!
            session['remote_session_token'] = @session.token
        end
        redirect_to root_path
    end

    def logout
        HTTParty.post("https://rlauth.phitherek.me/oauth/revoke?token=#{@session.token}")
        @session.destroy
        session.delete('remote_session_token')
        redirect_to root_path
    end

    def get_i18n
        render json: {i18n: I18n.t(params[:key], locale: params[:locale] || I18n.default_locale)}
    end

    private

    def auth_hash
        request.env['omniauth.auth']
    end

    def find_user
        if session['remote_session_token'] != nil
            @session = RemoteSession.find_by_token(session['remote_session_token'])
            if !@session.nil?
                @user = @session.remote_user
                @check = JSON.parse(HTTParty.get("https://rlauth.phitherek.me/api/user_data?access_token=#{@session.token}").body || "{}")
                if @check.include?("status") && @check["status"] == "failure"
                    session['remote_session_token'] = nil
                    redirect_to '/auth/rlauth' and return
                elsif @check.include?("user")
                    @user = RemoteUser.find_by_callsign(@check["user"]["callsign"])
                    if !@user.nil?
                        session['remote_session_token'] = @session.token
                    else
                        session['remote_session_token'] = nil
                    end
                end
            else
                @user = nil
            end
        else
            @user = nil
        end
    end

    def user_only
        redirect_to root_path unless !@user.nil?
    end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_main_nav.html.haml
- content_for :main_nav do
  .row
    .col-md-12
      %nav
        %ul.nav.nav-tabs
          %li{role: :presentation, class: @main_nav_active == :address ? 'active' : ''}= link_to t(".address"), address_path
          %li{role: :presentation, class: @main_nav_active == :ip ? 'active' : ''}= link_to t(".ip"), ip_path
          %li{role: :presentation, class: @main_nav_active == :pure ? 'active' : ''}= link_to t(".pure"), pure_path
          %li{role: :presentation, class: @main_nav_active == :reverse ? 'active' : ''}= link_to t(".reverse"), reverse_path

app/views/main/address.html.haml
= render partial: 'main_nav'
.query-form.address-query-form
  = form_for @loc, url: '#', method: :post, html: {class: 'form-horizontal'} do |f|
    .form-group
      .col-md-12
        = f.label :address, t(".enter_address")
        = f.text_field :address, required: true, class: 'form-control'
        %p.format_info.text-muted= t(".format_info")
    = f.submit t(:submit), class: 'btn btn-default'
.query-result-container{style: 'display: none;'}
  %h4.query-result-title
  .well.query-result
.query-error.alert.alert-danger{style: 'display: none;'}

app/views/main/geolocate.js.erb
navigator.geolocation.getCurrentPosition(GeoL);
function GeoL(position) {
    $("#pure_location_latitude").val(position.coords.latitude);
    $("#pure_location_longitude").val(position.coords.longitude);
}

app/views/main/history.html.haml
= link_to t(:home), root_path

%h2= t(:history)
- if @hqs.empty?
  .alert.alert-info= t(".no_hqs")
- else
  .row
    .col-md-12.text-center
      = paginate @hqs
  .row
    .col-md-12
      %table.table.table-striped.table-hover
        %thead
          %tr
            %th= t(".query")
            %th= t(".type")
            %th= t(".time")
        %tbody
          - @hqs.each do |hq|
            %tr
              %td= hq.location.kind_of?(AddressLocation) ? button_to(hq.location.address, address_path, params: {"address_location[address]": hq.location.address}, class: "link_button") : (hq.location.kind_of?(IpLocation) ? button_to(hq.location.ip, ip_path, params: {"ip_location[ip]": hq.location.ip}, class: "link_button") : (hq.location.kind_of?(PureLocation) ? button_to("#{hq.location.latitude} : #{hq.location.longitude}", pure_path, params: {"pure_location[latitude]": hq.location.latitude, "pure_location[longitude]": hq.location.longitude}, class: "link_button") : button_to(hq.location.locator, reverse_path, params: {"reverse_location[locator]": hq.location.locator}, class: "link_button")))
              %td= hq.location.kind_of?(AddressLocation) ? "address" : (hq.location.kind_of?(IpLocation) ? "ip" : (hq.location.kind_of?(PureLocation) ? "pure" : "reverse"))
              %td= hq.created_at.to_s
  .row
    .col-md-12.text-center
      = page_entries_info @hqs, entry_name: 'query'
  .row
    .col-md-12.text-center
      = paginate @hqs
= link_to t(:home), root_path

app/views/main/ip.html.haml
= render partial: 'main_nav'
.query-form.ip-query-form
  = form_for @loc, url: '#', method: :post, html: {class: 'form-horizontal'} do |f|
    .form-group
      .col-md-12
        = f.label :ip, t(".enter_ip")
        = f.text_field :ip, value: @loc.ip.nil? ? request.ip.to_s : @loc.ip, required: true, class: 'form-control'
        %p.format_info.text-muted= t(".format_info")
    = f.submit t(:submit), class: 'btn btn-default'
.query-result-container{style: 'display: none;'}
  %h4.query-result-title
  .well.query-result
.query-error.alert.alert-danger{style: 'display: none;'}

app/views/main/pure.html.haml
= render partial: 'main_nav'
.query-form.pure-query-form
  = form_for @loc, url: '#', method: :post, html: {class: 'form-horizontal'} do |f|
    .form-group
      .col-md-4
        = f.label :latitude, t(".enter_latitude")
        = f.number_field :latitude, required: true, step: "any", class: 'form-control'
    .form-group
      .col-md-4
        = f.label :longitude, t(".enter_longitude")
        = f.number_field :longitude, required: true, step: "any", class: 'form-control'
        %p.format_info.text-muted= t(".format_info")
    = f.submit t(:submit), class: 'btn btn-default pure-query-submit'
  = button_to t(:geolocate), geolocate_path, remote: true, method: :get, class: 'btn btn-default', form_class: 'button_to geolocation_button'
.query-result-container{style: 'display: none;'}
  %h4.query-result-title
  .well.query-result
.query-error.alert.alert-danger{style: 'display: none;'}

app/views/main/result.html.haml
.query-result-container
  %h4.query-result-title= t(".your_locator")
  .well.query-result= @loc.locator
= link_to t(:home), root_path, class: :index_link

app/views/main/reverse.html.haml
= render partial: 'main_nav'
.query-form.reverse-query-form
  = form_for @loc, url: '#', method: :post, html: {class: 'form-horizontal'} do |f|
    .form-group
      .col-md-12
        = f.label :locator, t(".enter_locator")
        = f.text_field :locator, required: true, class: 'form-control'
        %p.format_info.text-muted= t(".format_info")
    = f.submit t(:submit), class: 'btn btn-default'
.query-result-container{style: 'display: none;'}
  %h4.query-result-title
  .well.query-result
.query-error.alert.alert-danger{style: 'display: none;'}

app/views/main/reverse_result.html.haml
.query-result-container
  %h4.query-result-title= t(".your_address")
  .well.query-result= @loc.reverse_address
= link_to t(:home), root_path, class: :index_link