config/routes.rb
Rails.application.routes.draw do

  root to: redirect('/address')
  get '/logout', to: "main#logout"
  get '/auth/:provider/callback', to: "main#omniauth_callback", as: :omniauth_callback
  get '/address', to: "main#address"
  post '/address', to: "main#address_locator"
  get '/ip', to: "main#ip"
  post '/ip', to: "main#ip_locator"
  get '/pure', to: "main#pure"
  post '/pure', to: "main#pure_locator"
  get '/reverse', to: "main#reverse"
  post '/reverse', to: "main#reverse_query"
  get '/geolocate', to: "main#geolocate"
  get '/history', to: "main#history"
  get '/get_i18n', to: "main#get_i18n"
  post '/api/address', to: "api#address"
  post '/api/ip', to: "api#ip"
  post '/api/pure', to: "api#pure"
  post '/api/reverse', to: "api#reverse"
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %title RLQTH
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %header
        .page-header
          %h1
            RLQTH
            %small= t(:subtitle)
      - if flash[:notice]
        .flash.notice.alert.alert-info.alert-dismissible{role: 'alert'}
          %button{type: :button, class: :close, data: {dismiss: :alert}, 'aria-label': 'Close'}
            %span{'aria-hidden': :true} &times;
          = flash[:notice]
      - if flash[:error]
        .flash.error.alert.alert-danger.alert-dismissible{role: 'alert'}
          %button{type: :button, class: :close, data: {dismiss: :alert}, 'aria-label': 'Close'}
            %span{'aria-hidden': :true} &times;
          = flash[:error]
      .row
        .col-md-4.col-md-offset-4
          .userbox
            - if @user.nil?
              %p= t(:not_logged_in)
              = link_to t(:login), "/auth/rlauth"
            - else
              %p= t(:logged_in_as, callsign: @user.callsign)
              = link_to t(:history), history_path
              = link_to t(:logout), logout_path
      = content_for :main_nav if content_for? :main_nav
      .main
        = yield
      %footer
        %p.created_by= t(:created_by)
        %p.radiolog= t(:radiolog_tools)
        %p.address_geocoding= t(:address_geocoding)
        %p.ip_geocoding= t(:ip_geocoding)